#!/bin/bash
#

set -e

if [ -z $ANDROID_NDK_HOME ]; then
    echo "ANDROID_NDK_HOME env var must be set!"
    exit 1
fi

test -e $ANDROID_NDK_HOME || mkdir -p $ANDROID_NDK_HOME
cd $ANDROID_NDK_HOME

if [ ! -e $ANDROID_NDK_HOME/r9b ]; then
    if [ `uname -m` == 'x86_64' ] ; then
        SUFFIX='_64'
    else
        SUFFIX=''
    fi
    tar jxvf /vagrant/cache/android-ndk-r9b-linux-x86$SUFFIX.tar.bz2
    tar jxvf /vagrant/cache/android-ndk-r9b-linux-x86$SUFFIX-legacy-toolchains.tar.bz2
    mv android-ndk-r9b r9b
fi

if [ ! -e $ANDROID_NDK_HOME/r10e ]; then
    if [ `uname -m` == 'x86_64' ] ; then
       SUFFIX='_64'
    else
       SUFFIX=''
    fi
    7zr x /vagrant/cache/android-ndk-r10e-linux-x86$SUFFIX.bin > /dev/null
    mv android-ndk-r10e r10e
fi

chmod -R a+rX $ANDROID_NDK_HOME/
find $ANDROID_NDK_HOME/ -type f -executable -print0 | xargs -0 chmod a+x
