Vagrant::Config.run do |config|

  config.vm.box = "debian6-32"
  config.vm.box_url = "/shares/software/OS and Boot/debian6-32.box"

  config.vm.customize ["modifyvm", :id, "--memory", "1024"]

  config.vm.provision :shell, :path => "fixpaths.sh"
  # Set apt proxy - remove, or adjust this, accordingly!
  config.vm.provision :shell, :inline => 'sudo echo "Acquire::http { Proxy \"http://glencoe:3142\"; };" > /etc/apt/apt.conf.d/02proxy && sudo apt-get update'

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "cookbooks"
    chef.log_level = :debug 
    chef.json = {
      :settings => {
        :sdk_loc => "/home/vagrant/android-sdk",
        :ndk_loc => "/home/vagrant/android-ndk",
        :user => "vagrant"
      }
    }
    chef.add_recipe "android-sdk"
    chef.add_recipe "android-ndk"
    chef.add_recipe "fdroidbuild-general"
  end
end
