#!/bin/sh
#
# Simple pre-commit hook to check that there are no errors in the fdroid
# metadata files.

# Redirect output to stderr.
exec 1>&2

FILES="fdroid makebuildserver examples/*.py fdroidserver/*.py"

cmd_exists() {
	command -v $1 1>/dev/null
}

# For systems that switched to python3, first check for the python2 versions
if cmd_exists pyflakes-python2; then
	PYFLAKES=pyflakes-python2
elif cmd_exists pyflakes; then
	PYFLAKES=pyflakes
else
	echo "pyflakes is not installed!"
fi

if cmd_exists pep8-python2; then
	PEP8=pep8-python2
elif cmd_exists pep8; then
	PEP8=pep8
else
	echo "pep8 is not installed!"
fi

# If there are python errors or warnings, print them and fail.
[ -n "$PYFLAKES" ] && $PYFLAKES $FILES
#[ -n "$PEP8" ] && $PEP8 --ignore=E123,E501 $FILES
